"""
MAM session cookie management.

The `mam_id` cookie is the ONLY auth mechanism MAM exposes — every
HTTP call (.torrent grab, dynamic-seedbox ping, search probe) is
authenticated by attaching that cookie as an HTTP header. The cookie
is generated by the user via Preferences → Security on the MAM site,
locked to either an IP or an ASN, and (in practice) needs to be
rotated about once a month.

This module owns the auth layer the pipeline needs: HTTP client, IP
register flow, and cookie validation probe.

Two non-obvious choices, both load-bearing — do NOT change without a
real-world end-to-end check first:

  1. The `curl/8.0` User-Agent is intentional. MAM has bitten us with
     subtle UA-based rejection before, and this UA is verified against
     MAM end-to-end.
  2. `http2=False` is explicit. httpx can speak HTTP/2 when the `h2`
     package is installed; we pin HTTP/1.1 because that's what's been
     verified against MAM and we don't want variable transport
     behavior creeping in.

The validation probe deliberately uses MAM's search endpoint (a tiny
JSON POST) rather than scraping HTML. The endpoint is stable and
returns clear status codes.
"""
from __future__ import annotations

import asyncio
import json
import logging
from typing import Awaitable, Callable, Optional
from urllib.parse import urlparse

import httpx

_log = logging.getLogger("seshat.mam.cookie")


# ─── MAM endpoint constants ──────────────────────────────────

MAM_BASE_URL = "https://www.myanonamouse.net/"
MAM_SEARCH_URL = "https://www.myanonamouse.net/tor/js/loadSearchJSONbasic.php"
MAM_DYNIP_URL = "https://t.myanonamouse.net/json/dynamicSeedbox.php"


def _is_mam_url(url: str) -> bool:
    """True if `url` targets a myanonamouse.net host (any subdomain).

    Defense-in-depth host check used to gate URL fetches that attach
    the MAM session cookie. Replaces the previous `if "myanonamouse.net"
    in url` substring checks (CodeQL py/incomplete-url-substring-
    sanitization #25 / #28) which were bypassable via attacker URLs
    containing the literal substring elsewhere — e.g.
    `https://attacker.com/?u=myanonamouse.net` would have routed
    through MAM auth and leaked the session cookie to attacker.com.

    Accepts the apex `myanonamouse.net` plus any subdomain
    (`www.`, `t.`, `cdn.` — all three are in active use). Rejects
    anything that doesn't parse as a URL with a hostname.
    """
    if not url:
        return False
    try:
        host = (urlparse(url).hostname or "").lower()
    except Exception:
        return False
    if not host:
        return False
    return host == "myanonamouse.net" or host.endswith(".myanonamouse.net")

# Numeric category id for "Ebooks" — used by the validation probe to
# constrain the test search payload. The exact value doesn't matter
# much (we don't read any of the results), but we need a valid category
# or MAM may reject the payload.
_EBOOK_CATEGORY = "14"
_ENGLISH_LANG_ID = 1

# Tiny JSON payload sent to the search endpoint to verify auth. We
# don't care about the response body — we only need to know whether
# the request was accepted (cookie valid) or rejected (cookie invalid
# / IP mismatch / ASN mismatch). Pre-serialized so the body bytes go
# on the wire untouched (see _do_post for why).
_AUTH_PROBE_PAYLOAD = json.dumps(
    {
        "tor": {
            "text": "test",
            "srchIn": {"title": "true"},
            "searchType": "active",
            "searchIn": "torrents",
            "main_cat": [_EBOOK_CATEGORY],
            "browse_lang": [_ENGLISH_LANG_ID],
            "startNumber": "0",
        },
        "perpage": 5,
    }
)


# ─── Cookie auto-rotation state ──────────────────────────────
#
# MAM's backend dynamically rotates the `mam_id` cookie on every API
# call: each response carries a `Set-Cookie: mam_id=<new_value>`
# header. Clients that persist the new value get indefinite session
# lifetime (as long as they make at least one API call within a 15-day
# window); clients that ignore the new value keep using their original
# cookie and eventually hit MAM's max-age ceiling (~30 days in
# practice). Autobrr does the latter, which is why users historically
# have to rotate cookies manually every ~90 days. Seshat does it
# properly.
#
# Design:
#
#   - `_current_token` holds the most recently seen cookie value. It's
#     seeded from settings.json at startup via `set_current_token()`
#     and then updates automatically on every response.
#   - `_rotation_callback` is a user-supplied callable (set via
#     `set_rotation_callback()`) that gets awaited every time the
#     token changes. The lifespan wires this to a debounced
#     save_settings() call so persistence doesn't hammer the disk but
#     the saved value stays reasonably fresh.
#   - `_extract_mam_id_from_set_cookie()` parses the response's
#     `Set-Cookie` header(s) — note httpx exposes them via
#     `response.cookies` which is usually simpler, but we also keep a
#     regex fallback for the case where the jar normalization drops
#     attributes we care about.
#
# The rotation is INTENTIONALLY inline in `_do_get`/`_do_post` rather
# than in an httpx event hook. The hook API fires after httpx's own
# cookie jar has already merged the response cookies, which means we'd
# be racing against whatever the jar decided to do. Inline means we
# see the raw header on the response object exactly as MAM sent it.

_current_token: Optional[str] = None
_rotation_callback: Optional[
    Callable[[str], Awaitable[None]]
] = None

def set_current_token(token: str) -> None:
    """Seed the in-memory current token, usually from settings.json.

    Called by `main.py`'s lifespan right after `load_settings()`. Any
    subsequent `_do_get`/`_do_post` call that doesn't pass an explicit
    token will use this value, and successful responses will update
    it automatically via `_handle_response_cookie()`.
    """
    global _current_token
    _current_token = token


def get_current_token() -> str:
    """Return the most recently seen MAM session cookie.

    Returns empty string if nothing has been set yet. Used by
    `main.py`'s dispatcher rebuild and by tests that need to verify
    rotation captured the expected new value.
    """
    return _current_token or ""


async def get_active_token() -> str:
    """Resolve the active MAM session token from the canonical sources.

    Priority: in-memory rotated token → encrypted secrets store →
    settings.json (legacy fallback). This is the only correct way to
    fetch the cookie for an authenticated MAM API call: reading
    `settings.json["mam_session_id"]` directly returns whatever value
    was last written there, which can be weeks stale if the live
    cookie has been rotating in-memory + encrypted-store while the
    legacy settings field hasn't been touched. The status / refresh
    endpoint hit exactly that bug in v2.2.7.
    """
    token = get_current_token()
    if token:
        return token
    try:
        from app.secrets import get_secret
        token = await get_secret("mam_session_id")
        if token:
            return token
    except Exception:
        pass
    try:
        from app.config import load_settings
        return load_settings().get("mam_session_id", "") or ""
    except Exception:
        return ""


def set_rotation_callback(
    callback: Optional[Callable[[str], Awaitable[None]]],
) -> None:
    """Register an async function to be invoked on every cookie rotation.

    The callback is called with the new token string. Exceptions raised
    from the callback are logged but swallowed — rotation notification
    failures must not prevent the request that produced the new cookie
    from returning cleanly to its caller. Pass None to clear the
    callback (used by the lifespan on shutdown).
    """
    global _rotation_callback
    _rotation_callback = callback


def _extract_mam_id_from_response(response: httpx.Response) -> Optional[str]:
    """Pull the new mam_id value out of a MAM response, or None.

    Reads from httpx's cookie jar exclusively. The jar honors RFC 6265
    expiration semantics (Max-Age=0, Expires-in-the-past), so deletion
    sentinels MAM sends to terminate a session — `Set-Cookie:
    mam_id=deleted; Max-Age=0` and friends — correctly produce None
    here rather than a "rotation" to the literal string "deleted".

    The previous implementation had a regex fallback against raw
    Set-Cookie headers for "edge cases where httpx drops cookies",
    but the fallback ignored expiration attributes and captured
    deletion sentinels as rotations. On 2026-05-09 this corrupted
    the discovery module's parallel `_current_token` slot after a
    rejected filelist fetch, which then 403'd every subsequent search
    in the live container until restart. Removed; trust httpx's
    RFC implementation.
    """
    return response.cookies.get("mam_id")


async def _handle_response_cookie(response: httpx.Response) -> None:
    """Check a MAM HTTP response for a rotated cookie and apply it.

    Called from `_do_get` and `_do_post` after every successful
    request. Compares the new value (if any) to `_current_token`; if
    they differ, updates the in-memory state and fires the rotation
    callback. Logs at INFO during Phase 1 (Loud mode) so we can watch
    rotation working in production logs during the smoke test; the
    log level should drop to DEBUG in Phase 3 once we're confident
    the mechanism is reliable.
    """
    global _current_token
    new_token = _extract_mam_id_from_response(response)
    if not new_token:
        return
    if new_token == _current_token:
        return  # no-op: MAM sent back the same cookie (rare but valid)

    # Don't log token bytes, even a prefix — an 8-char prefix is
    # enough entropy to correlate sessions across log aggregators,
    # and anyone with `docker logs` access is a wider audience than
    # the people authorized to see the MAM session token. The fact-
    # of-rotation is the only diagnostic that matters here.
    _log.info("MAM rotated session cookie; persisting")
    _current_token = new_token

    # Fire the rotation callback. Failures here must not propagate —
    # the MAM request that produced this rotation already succeeded,
    # and a callback error (e.g. disk full for settings.json) should
    # never make the caller see the request as failed.
    callback = _rotation_callback
    if callback is not None:
        try:
            await callback(new_token)
        except Exception:
            _log.exception("rotation callback raised; cookie is still updated in-memory")


# ─── HTTP layer ──────────────────────────────────────────────

_client: Optional[httpx.AsyncClient] = None


def build_headers(token: str) -> dict[str, str]:
    """Build the standard MAM request headers for a given session token.

    Public so the grab path (`mam.grab`) can reuse the exact same
    header set when fetching .torrent files. Keeping the construction
    in one place means a UA change or a header tweak is a single edit.
    """
    return {
        "Content-Type": "application/json",
        "User-Agent": "curl/8.0",
        "Cookie": f"mam_id={token}",
    }


def get_client() -> httpx.AsyncClient:
    """Lazy-initialized module-level httpx.AsyncClient for connection reuse.

    MUST be called from within a running asyncio event loop — the
    client binds to whichever loop is active at creation time.
    Seshat runs one uvicorn loop for the whole process lifetime, so
    this is safe.
    """
    global _client
    if _client is None:
        _client = httpx.AsyncClient(
            http2=False,
            timeout=httpx.Timeout(20.0, connect=10.0),
            follow_redirects=True,
        )
        _log.debug("MAM httpx.AsyncClient created")
    return _client


async def aclose_session() -> None:
    """Tear down the module-level AsyncClient.

    Called from `main.py`'s lifespan during app shutdown. Safe to call
    multiple times — subsequent calls are no-ops. The `a` prefix is
    deliberate: callers must `await` to actually close the underlying
    transport.
    """
    global _client
    if _client is not None:
        try:
            await _client.aclose()
            _log.debug("MAM httpx.AsyncClient closed")
        except Exception as e:
            _log.warning(f"Error closing MAM client: {e}")
        finally:
            _client = None


def _resolve_token(explicit: Optional[str]) -> str:
    """Pick the token to use for a request.

    If the caller passed an explicit token (validation probe, test
    fixture, etc.), use that. Otherwise fall back to the module-level
    `_current_token` which is kept fresh by the rotation handler.
    Empty string is returned if neither is set — callers are expected
    to treat that as "no auth" and let MAM reject the request.
    """
    if explicit:
        return explicit
    return _current_token or ""


async def _do_get(
    url: str, token: Optional[str] = None, timeout: int = 15
) -> httpx.Response:
    """Async GET to a MAM endpoint with the standard auth header set.

    Automatically rotates the in-memory token if the response carries
    a new `mam_id` cookie — see `_handle_response_cookie`. The rotation
    fires BEFORE the response is returned to the caller so that if the
    caller immediately uses the rotated token for another request
    (e.g. a grab followed by a validation check), it sees the fresh
    value.

    HOST GATE: rejects any URL that doesn't target a myanonamouse.net
    host (CodeQL py/full-ssrf #26 defense-in-depth). This client
    attaches the MAM session cookie — sending it to a non-MAM host
    would leak credentials. All legitimate callers either use a
    MAM_*_URL constant or have already host-checked their input via
    `_is_mam_url` before calling.
    """
    if not _is_mam_url(url):
        raise ValueError(
            f"_do_get refuses non-MAM URL (cookie would leak): {url!r}"
        )
    effective_token = _resolve_token(token)
    response = await get_client().get(
        url, headers=build_headers(effective_token), timeout=timeout
    )
    await _handle_response_cookie(response)
    return response


async def _do_post(
    url: str,
    token: Optional[str] = None,
    payload: str = "",
    timeout: int = 20,
) -> httpx.Response:
    """Async POST to a MAM endpoint with the standard auth header set.

    `payload` MUST be a pre-serialized JSON string. Sent via httpx's
    `content=` parameter so the body bytes go on the wire untouched.
    `data=<dict>` (form-url-encoded) and `json=<dict>` (re-serialized
    by httpx) both break the MAM search API in subtle ways: MAM
    happily accepts the request and returns HTTP 200 with a zero-byte
    body, which looks exactly like an auth failure but isn't. The fix
    is sending exact JSON bytes.

    Automatically rotates the in-memory token if the response carries
    a new `mam_id` cookie.
    """
    effective_token = _resolve_token(token)
    response = await get_client().post(
        url,
        headers=build_headers(effective_token),
        content=payload,
        timeout=timeout,
    )
    await _handle_response_cookie(response)
    return response


# ─── Validation flow ─────────────────────────────────────────


async def register_ip(token: str, skip_ip_update: bool = True) -> dict:
    """Ping MAM's dynamic-seedbox endpoint to register the server's IP.

    Most users (Seshat included by default) lock their session to an
    ASN rather than a single IP, in which case this call is unnecessary
    and the function short-circuits to success without hitting MAM.
    The `skip_ip_update=True` default reflects the safer common case;
    set it to False on a per-call basis if you know your session is
    IP-locked rather than ASN-locked.

    Returns: `{"success": bool, "message": str, ...optional fields}`.
    Never raises — failures come back as `success=False` with a
    human-readable message ready for the UI.
    """
    if skip_ip_update:
        return {
            "success": True,
            "message": "Skipped IP registration (ASN-locked session)",
        }

    _log.info("Registering server IP with MAM...")

    try:
        resp = await _do_get(MAM_DYNIP_URL, token)
        body = resp.text.strip()
        _log.debug(f"IP registration response: {body}")

        # MAM dynamicSeedbox.php returns JSON like:
        #   {"Success": true, "msg": "Completed", "ip": "...",
        #    "ASN": 12345, "AS": "..."}
        # On failure msg may be "No Session Cookie", "Invalid session -
        # IP mismatch", "Last Change too recent", etc.
        try:
            data = resp.json()
        except Exception:
            if "<html" in body.lower():
                return {
                    "success": False,
                    "message": "Got HTML login page — token wrong or expired",
                }
            return {
                "success": False,
                "message": f"Non-JSON response: {body[:200]}",
            }

        msg = str(data.get("msg", "")).strip()
        if data.get("Success"):
            _log.info(f"IP registration OK ({msg or 'no message'})")
            return {
                "success": True,
                "message": msg or "OK",
                "ip": data.get("ip"),
                "asn": data.get("ASN"),
                "as_org": data.get("AS"),
            }

        # Success=false branch — translate known msg values to clear
        # human-readable messages for the UI.
        msg_l = msg.lower()
        if "incorrect session type" in msg_l:
            _log.warning("ASN-locked session — IP registration not needed")
            return {
                "success": True,
                "message": "ASN-locked session — IP registration not needed",
            }
        if "no session cookie" in msg_l or "invalid cookie" in msg_l:
            return {
                "success": False,
                "message": "Token not recognized by MAM",
            }
        if "ip mismatch" in msg_l or "asn mismatch" in msg_l:
            return {
                "success": False,
                "message": f"Session locked to a different network: {msg}",
            }
        if "too recent" in msg_l:
            return {
                "success": False,
                "message": f"IP change rate-limited by MAM: {msg}",
            }
        return {
            "success": False,
            "message": msg or f"Unexpected response: {body[:200]}",
        }
    except asyncio.TimeoutError:
        return {"success": False, "message": "Timeout connecting to MAM"}
    except Exception:
        # Log the full traceback server-side but return a generic
        # message: exception details can leak library versions,
        # internal hostnames, or stack frame paths through API
        # response bodies.
        _log.exception("MAM IP-registration network error")
        return {
            "success": False,
            "message": "Network error connecting to MAM dynamic seedbox endpoint",
        }


async def verify_session(token: str) -> dict:
    """Probe the MAM search endpoint to verify the cookie is accepted.

    Returns: `{"success": bool, "message": str}`.

    The probe payload is a tiny English ebook search — we don't read
    the results, we only care whether MAM accepted the request. A
    HTTP 200 with a non-empty body means the cookie is valid; HTTP 200
    with a zero-byte body or HTTP 403 means the cookie is rejected.
    """
    _log.info("Verifying MAM session cookie...")

    try:
        resp = await _do_post(MAM_SEARCH_URL, token, _AUTH_PROBE_PAYLOAD, 15)
        if resp.status_code == 200 and len(resp.text) > 0:
            _log.info("MAM session cookie OK")
            return {"success": True, "message": "Connection successful"}
        if resp.status_code == 200 and len(resp.text) == 0:
            return {
                "success": False,
                "message": "HTTP 200 but empty response — token may be invalid or expired",
            }
        if resp.status_code == 403:
            return {
                "success": False,
                "message": "HTTP 403 — session rejected. Check token validity for this server's IP/ASN.",
            }
        return {
            "success": False,
            "message": f"Unexpected HTTP {resp.status_code}",
        }
    except Exception:
        _log.exception("MAM session-verify network error")
        return {
            "success": False,
            "message": "Network error verifying MAM session",
        }


async def validate(token: str, skip_ip_update: bool = True) -> dict:
    """Full validation: IP registration (if applicable) + session probe.

    Composite of `register_ip` and `verify_session`. Used by the
    background cookie-check job and by the Settings UI's "test cookie"
    button. Returns the same shape as `verify_session` plus the
    sub-results so the UI can show which step failed.
    """
    if not token:
        return {
            "success": False,
            "message": "No MAM session cookie configured",
            "ip_result": None,
            "search_result": None,
        }

    ip_result = await register_ip(token, skip_ip_update)
    if not ip_result["success"]:
        return {
            "success": False,
            "message": f"IP registration failed: {ip_result['message']}",
            "ip_result": ip_result,
            "search_result": None,
        }

    search_result = await verify_session(token)
    return {
        "success": search_result["success"],
        "message": (
            search_result["message"]
            if search_result["success"]
            else f"Session verify failed: {search_result['message']}"
        ),
        "ip_result": ip_result,
        "search_result": search_result,
    }
